controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    leo1_velocity_controller:
      type: diff_drive_controller/DiffDriveController

    leo2_velocity_controller:
      type: diff_drive_controller/DiffDriveController

leo1_velocity_controller:
  ros__parameters:
    left_wheel_names: [ "rover1/wheel_FL_joint", "rover1/wheel_RL_joint" ]
    right_wheel_names: [ "rover1/wheel_FR_joint", "rover1/wheel_RR_joint" ]

    wheel_separation: 0.33
    wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.0625

    wheel_separation_multiplier: 1.17
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 20.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal : [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0001, 0.0, 0.0, 0.0, 0.0, 0.0001]

    open_loop: false
    enable_odom_tf: false

    cmd_vel_timeout: 0.25
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Preserve turning radius when limiting speed/acceleration/jerk
    preserve_turning_radius: true

    # Publish limited velocity
    publish_cmd: true

    # Publish wheel data
    publish_wheel_data: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.4
    linear.x.min_velocity: -0.4
    linear.x.max_acceleration: 0.8
    linear.x.min_acceleration: -0.8
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 2.0
    angular.z.min_acceleration: -2.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0
