### ekf config file ###
ekf_filter_node:
    ros__parameters:
        use_sim_time: false
        frequency: 30.0
        sensor_timeout: 0.3
        two_d_mode: true
        print_diagnostics: true
        publish_tf: false
        map_frame: map                      # Defaults to "map" if unspecified
        odom_frame: odom                    # Defaults to "odom" if unspecified
        base_link_frame: base_footprint     # Defaults to "base_link" if unspecified
        world_frame: room_map               # Defaults to the value of odom_frame if unspecified

# The filter accepts an arbitrary number of inputs from each input message type (nav_msgs/Odometry,
# geometry_msgs/PoseWithCovarianceStamped, geometry_msgs/TwistWithCovarianceStamped,
# sensor_msgs/Imu). 
        #        [x_pos   , y_pos    , z_pos,
        #         roll    , pitch    , yaw,
        #         x_vel   , y_vel    , z_vel,
        #         roll_vel, pitch_vel, yaw_vel,
        #         x_accel , y_accel  , z_accel]

        odom0: /odom/robot  # odometry of the camera
        odom0_config: [false, false, false,
                       true, true, true,
                       true, true, true,
                       true, true, true,
                       true, true, true]

        odom1: /odom/gps    # odometry from the beacons
        odom0_config: [true, true, true,
                       false, false, false,
                       false, false, false,
                       false, false, false,
                       false, false, false]